name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build --configuration Release
    - name: Read Version
      id: version
      run: echo "::set-output name=version::$(cat version.txt)"
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          NansUtils/bin/Release/net5.0/NansUtils.dll
        name: NansUtil v${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 