name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Changed to windows for better .NET Framework compatibility

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
        
    - name: Restore NuGet packages
      run: nuget restore NansUtils.sln
        
    - name: Build Plugin
      run: |
        msbuild NansUtils.sln /p:Configuration=Release /p:Platform="Any CPU"
        
    - name: Read Version
      id: version
      run: echo "::set-output name=version::$(type version.txt)"
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/Release/NansUtils.dll
        name: NansUtils v${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }} 